### ISSUE TITLE
grunt-contrib-eslint doesn't work with eslint 1.0.0

### ISSUE THREAD

**Issue by klausbayrhammer** [gyandeeps/gruntify-eslint#9]
eslint released [v1.0.0](https://github.com/eslint/eslint/releases/tag/v1.0.0) and made some breaking changes. When running the grunt-eslint-task with eslint v1.0.0 the following error occurs:

```
Warning: Cannot read property 'execute' of undefined Use --force to continue.
TypeError: Cannot read property 'execute' of undefined
    at Object.<anonymous> (/src/node_modules/grunt-contrib-eslint/tasks/eslint.js:21:26)
    at Object.<anonymous> (/src/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/src/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/src/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/src/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/src/node_modules/grunt/lib/util/task.js:300:12)
    at /src/node_modules/grunt/lib/util/task.js:227:11
    at doNTCallback0 (node.js:408:9)
    at process._tickDomainCallback (node.js:378:13)
    at Function.Module.runMain (module.js:469:11)
```

Is grunt-contrib-eslint in the npm-registry still maintained or should we swtich to gruntify-eslint?

**Comment by p-m-p** [comment]
I forked this to patch it but looks like the work is already done https://github.com/gyandeeps/gruntify-eslint/compare/v0.1.1...master

Can we get it published? Thanks.

**Comment by gyandeeps** [comment]
@p-m-p @klausbayrhammer Guys sorry about that. I have the changes already merged. 
I will release in next 5 mins. Make sure if you use eslint `1.0.0`, your dependency for gruntify-eslint is also `1.0.0`.

**Comment by gyandeeps** [comment]
I have released `1.0.0` version. https://github.com/gyandeeps/gruntify-eslint/releases/tag/v1.0.0
Use this if you are using `eslint` 1.0 version.

**Comment by gyandeeps** [comment]
Please install using the name `gruntify-eslint`

**Comment by p-m-p** [comment]
No worries dude, thanks for the quick update!
